### ISSUE TITLE
Inserir card de usuarios no MANAGE USER

### ISSUE THREAD

**Issue by juliotoscano** [amadeusproject/uxdesign-html#11]

**Comment by fbormann** [comment]
@juliotoscano  tem como tu descrever o que foi feito nessa tela? pra eu poder validar e passar pra "Done"

**Comment by juliotoscano** [comment]
Eu coloquei o card do usuario e padronizei com as outras telas.

**Comment by fbormann** [comment]
Existem dois arquivos:"manager_user.html" e "manage_user.html", decide qual dos dois será utilizado, remove um e comita o outro.

**Comment by fbormann** [comment]
![manage_user](https://cloud.githubusercontent.com/assets/2985027/18251543/049f15b8-7360-11e6-9940-86550f8b6916.jpg)

Segue a imagem-fonte da Issue. 
Problema 1: Para cada user existem dois butões: "edit" e "delete". Não foram adicionados, não existe botão "go" no ux.

Problema 2: Adicionar "title": " manage users".
