### ISSUE TITLE
Create new application icon set

### ISSUE THREAD

**Issue by santojon** [amadeusproject/uxdesign-html#13]

**Comment by santojon** [comment]
Create Amadeus logos and icons to fit new application needs

**Comment by thiagosoara** [comment]
Glau,

essa issue é da Sprint 2, preciso que você resolva isso com urgência para não atrasar o cronograma. Como anda essa atividade, já pode fechar?

**Comment by juliotoscano** [comment]
@santojon Essa atividade como está?
