### ISSUE TITLE
Criar o template HOME (Módulo Student)

### ISSUE THREAD

**Issue by juliotoscano** [amadeusproject/uxdesign-html#2]

**Comment by fbormann** [comment]
[PT-BR]
Problemas:
 - Não possui links onde deveria possuir (Link pro perfil, link nos headers(neste caso, procure o novo header.html em "base")
- Não possui breadcrumbs 

[EN]

Problems:
- Doesn't possess all links already established (the profile one as well as header's).
- Breadcrumbs aren't here.
