### ISSUE TITLE
[Atividade]Criar o Card Forum

### ISSUE THREAD

**Issue by pvcs15** [amadeusproject/uxdesign-html#25]

**Comment by fbormann** [comment]
Eu supus que todos os files com nome "forum" dentro da pasta "cards" fizeram parte desta issue.
- Em form_newform.html todos os includes estão com paths errados.
- Acho que form_forumcomment.html não está com os includes pois estava no padrão que @thiagosoara tinha proposto. No demais, o código parece correto.
Em forum.html
- Uma tag "p" é aberta na linha 3 e não é fechada.

**Comment by japm94** [comment]
improving

**Comment by japm94** [comment]
improving

**Comment by japm94** [comment]
forum teacher e student finished

**Comment by fbormann** [comment]
onde eles foram adicionados @japm94 ?

**Comment by fbormann** [comment]
Só possui erro gramatical nos forms:
 - "Opened in:" ao invés de "Onpened in"
-  sugestão 1: importante @japm94 @santojon , até pra criar uma issue nova, talvez, colocar uma textArea ao invés de textField.
- Sugestão 2: Ser o timestamp da resposta (5 minutos atrás) ao invés da data exata. 
Passei pra refactoring pra discussão continuar.

**Comment by japm94** [comment]
Ajustado FORUM em cards/topic.html
