### ISSUE TITLE
[Material]Card de inclusão de Links

### ISSUE THREAD

**Issue by pvcs15** [amadeusproject/uxdesign-html#26]
- [ ] Integrar card à screen correspondente.

**Comment by fbormann** [comment]
Porque isso está em Review? não existe material nenhum relacionado à ele.

**Comment by japm94** [comment]
Erro meu.

Em 11/09/2016 1:03 PM, "Felipe Bormann" <notifications@github.com> escreveu:

**Comment by fbormann** [comment]
Não commits relacionados à esta issue, então supus que deveria rever o arquivo: "/html/components/cards/links.html"
Eu não consegui testar ele corretamente pois não  está listado em nenhum commit para esta issue no qual ele esteja inserido em uma page. Qual page eu posso testar ele?

**Comment by japm94** [comment]
home_subctec_teacher -> Topic -> Links. Na parte de card tem link edit, link_new, link

**Comment by thiagosoara** [comment]
@fbormann Preciso que tu faça o review dessa atividade. Eu acredito que já foi feita.

**Comment by juliotoscano** [comment]
@japm94 Nao estou encontrando esse card integrado a uma screen. Precisa estar integrado para que a atividade possa ser fechada.
