### ISSUE TITLE
Criar o template PARTICIPANTS

### ISSUE THREAD

**Issue by juliotoscano** [amadeusproject/uxdesign-html#30]
Obs: Lembrar que será somente 1 tela de participantes sendo acessada por aluno e por professor. (1 tela para os dois tipos de usuario)

- [x] Card de professores ou tutores que participam do curso

- [x] Card de alunos que participam do curso

- [x] Icone de presença do usuario.(Mostrando que o participante está online ou nao)

- [x] Mostrar nome e email dos participantes.

- [x] Ao clicar na foto, mostrar o perfil do participante.

**Comment by fbormann** [comment]
Não tem commit associado à esta tarefa, não sei qual tela é, nem o nome do arquivo.

**Comment by japm94** [comment]
Done

**Comment by fbormann** [comment]
Sim @japm94 , tem o nome do arquivo?!

**Comment by japm94** [comment]
screen/participants.html

**Comment by fbormann** [comment]
![participants](https://cloud.githubusercontent.com/assets/2985027/18843586/02beab5a-83f0-11e6-8d4c-41000768dc1b.png)
é assim que a tela se encontra, irei mandar para Refactoring.

**Comment by japm94** [comment]
Não tava conseguindo linkar o css

**Comment by japm94** [comment]
Consertado. Precisa agora ajeitar o padding dos nomes

**Comment by japm94** [comment]
Consertado. Precisa agora ajeitar o padding dos nomes

**Comment by thiagosoara** [comment]
@japm94 screen/participants.html esse cara não existe, qual o status dessa issue? Qual arquivo @fbormann precisa revisar para fecharmos ela?

**Comment by japm94** [comment]
Eu commito, mas não vai. Ela ta em course_participants_student e course_participants_teacher
