### ISSUE TITLE
Criar o template EDIT_PROFILE

### ISSUE THREAD

**Issue by juliotoscano** [amadeusproject/uxdesign-html#31]
- [x] Inserir mesmos campos de cadastros.

- [x] Inserir campo para mudar imagem de perfil.

**Comment by fbormann** [comment]
Alguns campos de preenchimento estão desalinhados com seus respectivos "field names".

**Comment by pvcs15** [comment]
eu nao consegui alinhar. tambem não sei o motivo deles estarem desalinhados. alguma ajuda?

**Comment by fbormann** [comment]
Ainda desalinhado.

**Comment by pvcs15** [comment]
atualizei la bormann, da uma olhada
