### ISSUE TITLE
Criar o CRUD do TOPIC

### ISSUE THREAD

**Issue by juliotoscano** [amadeusproject/uxdesign-html#33]
- [x] Criar modal para formulário de criação de tópico.

- [x] Permitir que o professor possa editar o Tópico (Utilizar o mesmo formulário de criação).

- [x] Permitir ao professor remover tópico (Deve aparecer um popup antes de se confirmar a remoção).

Obs: De preferência, realizar as três etapas utilizando modal.

**Comment by fbormann** [comment]
- Quando clico em "remover" no tópico, não existe link para modal perguntando se ele quer confirmar a remoção.

**Comment by pvcs15** [comment]
tas olhando no canto certo amigo bormann? nos 3 pontinhos ali em topico, tem la remover. clique la pfv

**Comment by fbormann** [comment]
Sim @pvcs15 , em subject tem, mas em tópico, não.

**Comment by juliotoscano** [comment]
@fbormann Realmente aparece a mensagem. Acho que o Js está dando um 'delay' e é preciso clicar duas vezes para que ele funcione. Creio que quando passar isso para o back, acaba se resolvendo com 1 unico click.
