### ISSUE TITLE
Criar o CRUD do SUBJECT

### ISSUE THREAD

**Issue by juliotoscano** [amadeusproject/uxdesign-html#34]
- [x] Criar template para a criação do subject.

- [x] Permitir que o professor Edit o subject utilizando o mesmo formulário de criação.

- [x] Permitir que o professor remova o Subject (Mostrar popup de confirmação antes da remoção)

**Comment by fbormann** [comment]
Pergunta: aquele botão acess vai ser ali mesmo? naquele menu à direita? e não a barra inteira? 
Só existe um erro conceitual: 
- Existem mais de uma div com o mesmo id, id é um seletor único, se for pra modificar mais de uma, utilize uma classe.

**Comment by juliotoscano** [comment]
O botão ficou com access pq essa questão de acesso nao foi definido como ficaria.

**Comment by juliotoscano** [comment]
aonde está esse id repetido? em que card?

**Comment by fbormann** [comment]
Vamos levar a discussão desse botão para a reunião terça, @juliotoscano , e sobre o id repetido foi erro meu. Vi na mesma atividade mas eles estão em files diferentes que não pertencem a mesma tela, então pode. Vou dar closed nesta tarefa.
