### ISSUE TITLE
Criar o template HOME_SUBJECT_STUDENT

### ISSUE THREAD

**Issue by juliotoscano** [amadeusproject/uxdesign-html#4]

**Comment by thiagosoara** [comment]
@juliotoscano parceiro, as referencias para o css estão erradas, ajeita o css que não está abrindo, pelo que vi basta tirar um "../" do path

**Comment by pvcs15** [comment]
Julio a parte de notificaçoes esta abrindo atras do card principal. Vê se tu sabe arrumar isso, se nao puder avisa que eu vejo aqui

**Comment by pvcs15** [comment]
Julio a parte de notificaçoes esta abrindo atras do card principal. Vê se tu sabe arrumar isso, se nao puder avisa que eu vejo aqui

**Comment by juliotoscano** [comment]
@pvcs15 arruma isso porfavor. Eu coloquei mas nao deu para consertar.
