### ISSUE TITLE
Modificar HOME para novo padrão definido

### ISSUE THREAD

**Issue by juliotoscano** [amadeusproject/uxdesign-html#40]
- [ ] Utilizar componentes gerais na sua Screen principal (Ex: o header, pending stuffs, etc)

- [ ] Criar os componentes novos que são necessários para a screen principal.

- [ ] Permitir conexão com outras paginas através dos links.

**Comment by japm94** [comment]
Did, but improving

**Comment by japm94** [comment]
Links ajeitados

**Comment by fbormann** [comment]
Done.
