### ISSUE TITLE
Modificar HOME_SUBJECT para novo padrão definido

### ISSUE THREAD

**Issue by juliotoscano** [amadeusproject/uxdesign-html#43]
- [x] Utilizar componentes gerais na sua Screen principal (Ex: o header, pending stuffs, etc)

- [x] Criar os componentes novos que são necessários para a screen principal.

- [x] Permitir conexão com outras paginas através dos links.

- [x] Linkar com arquivos css e js

**Comment by fbormann** [comment]
Não consigo revisar a tela funcional, então chequei os códigos.
No arquivo home_subject_teacher.html: 
- a div com classe "row" está externa à div de classe "container-fluid", a ordem é inversa.
- Existem quatro divs que juntas dão mais de 12 colunas, isto é conceitualmente errado no bootstrap.

**Comment by juliotoscano** [comment]
Concertado.

**Comment by juliotoscano** [comment]
@fbormann Essa atividade já pode ser fechada.

**Comment by fbormann** [comment]
Fechada.
