### ISSUE TITLE
Criar o template COURSE_DETAIL

### ISSUE THREAD

**Issue by juliotoscano** [amadeusproject/uxdesign-html#44]
- [x] Utilizar componentes gerais na sua Screen principal (Ex: o header, pending stuffs, etc)

- [x] Criar os componentes novos que são necessários para a screen principal.

- [x] Permitir conexão com outras paginas através dos links.

Essa pagina contem um card com a descrição do curso selecionado e abaixo seus respectivos subjects. Os subjects devem posssuir botões que leve o usuario ao HOME_SUBJECT

**Comment by fbormann** [comment]
Só cometeu o mesmo erro que em outra issue feita por @juliotoscano , pode checar no commit 5108a01 ,  os seguintes erros:
- Div "row" externa à div "container-fluid". 
- E divs no mesmo nível (pense no html como uma árvore), possuirem colunas que somadas dão mais de 12.

**Comment by thiagosoara** [comment]
@vinniemoreira @fbormann 
is it done?

**Comment by juliotoscano** [comment]
acabei de verificar @thiagosoara , está feito.
