### ISSUE TITLE
Criar o template HOME_COURSE

### ISSUE THREAD

**Issue by juliotoscano** [amadeusproject/uxdesign-html#47]

**Comment by juliotoscano** [comment]
Pessoal, eu coloquei esses icones e achei que ficaram muito bons. Mas sendo que eu nao consegui alinhar com o header do card course ainda. Depois vou tentar resolver isso. Se alguem souber como resolver isso pode ajudar. :)

**Comment by juliotoscano** [comment]
Esta feito.

**Comment by fbormann** [comment]
Done.
