### ISSUE TITLE
Padronizando paginas

### ISSUE THREAD

**Issue by juliotoscano** [amadeusproject/uxdesign-html#48]
- [x] Login 

- [x] Register user

- [x] Add material design

- [x] Crud topic

- [x] Page Home_student

- [x] Linkar paginas

**Comment by fbormann** [comment]
O que era pra ser feito nesta Issue, @juliotoscano ? Vi seus commits há pouco  e vi que alguns arquivos seguiram um padrão mesmo. (e as URLs também). Mas só confirma o que esperar desta issue. Obrigado

**Comment by juliotoscano** [comment]
A principio, organizar para apresentar na reuniao back. mas nao deu certo. Consertei algumas coisas hoje.

**Comment by juliotoscano** [comment]
@fbormann eu acho que essa atividade pode ser fechada. O objetivo dela ja foi atingida, padronizar certas paginas para apresentação na reuniao. Como a reuniao ja passou entao podemos finalizar.

**Comment by fbormann** [comment]
Ok, finalizei.
