### ISSUE TITLE
Modificar ações sobre objetos

### ISSUE THREAD

**Issue by santojon** [amadeusproject/uxdesign-html#57]
- Ações sobre objetos devem estar neles mesmos
Verificar e corrigir para:

- [x] Topic
- [x] Subject
- [x] Course

O que verificar:

- [x] Localização de botões e links de ação transformativa do objeto (edit, delete, show/hide)
- [x] Corrigir posicionamento do checkbox de visibilidade e remover caixa de seleção (manter apemas ícone)
- [x] Corretude dos ícones ()se são os certos para cada ação

**Comment by juliotoscano** [comment]
QUe botão é esse "show/hide"? o que ele faz?

**Comment by fbormann** [comment]
Os ícones parecem estar de acordo com a sua semântica.
As tarefas foram feitas.
(chequei através do design).
