### ISSUE TITLE
Remover comportamento 'accordion' nas listagens

### ISSUE THREAD

**Issue by santojon** [amadeusproject/uxdesign-html#59]
Verificar e corrigir para:

- [x] Course (listagem de courses, detalhes de course)
- [x] Subject (detalhes de subject)

**Comment by juliotoscano** [comment]
Nao entendi essa atividade, nao vai ter mais accordion nas listas?

**Comment by juliotoscano** [comment]
Ainda estou com duvida nessa atividade.

**Comment by thiagosoara** [comment]
Vai sim, a questão deve ser não fechar um quando abrir outro.

**Comment by juliotoscano** [comment]
Eu tentei fazer isso essa semana mas quando eu coloco, é como se o js que está la atrapalha-se o jquery ai eu nao consigo usar.

**Comment by juliotoscano** [comment]
Pronto.

**Comment by fbormann** [comment]
Não considero pronto porque: 
- Você utilizou id's para modificar elementos que terão vários outros que terão os mesmos comportamentos, em topic tem "#divMoreActions" e a outra era "#headingTwo". Bom discutirmos isto ai.

**Comment by juliotoscano** [comment]
Blz, vou colocar como class
