### ISSUE TITLE
Criar card de DELIVERY_EXERCISE (após envio)

### ISSUE THREAD

**Issue by santojon** [amadeusproject/uxdesign-html#63]
Lembrar de atender às visões:

- [ ] Student
- [ ] Teacher

**Comment by juliotoscano** [comment]
@pvcs15 
O campo de pesquisa por estudante esta desalinhado.
Icone no card do aluno está muito próximo ao nome do aluno.
Não há botão para o professor enviar a nota.
O pagination também está desalinhado.
Está faltando a visão do aluno.

**Comment by juliotoscano** [comment]
Endereço do breadcrumb errado. Tem que ser Home > courses > course01 > subject > activitie01

**Comment by pvcs15** [comment]
a visão do aluno, eu fiz um card separado. esta na pasta de card

**Comment by pvcs15** [comment]
Julio veja o a pagina (pos envio do aluno) exercise_teacher. esta com o alinhamento e o botao de submit
