### ISSUE TITLE
Criar paginação e inserir campos de busca na listagem de cursos

### ISSUE THREAD

**Issue by santojon** [amadeusproject/uxdesign-html#64]

**Comment by vinniemoreira** [comment]
Se vocês forem ver a page, o breadcrumb tá com um padding-down grande, provavelmente é o css do breadcrumb ou da class input-group, que tá deixando a barra de busca estranha.

**Comment by santojon** [comment]
@vinniemoreira, a classe form-group do material bootstrap tem margin: 28px; Você tem que colocar uma classe a mais nessa div que dê override nesse valor, ou seja, techa margin: 0 (ou o valor necessário) !important; essa classe deve ser criada em amadeus.css, na área reservada a overrides

**Comment by fbormann** [comment]
Pagination funcionando. E campo de busca correto.
