### ISSUE TITLE
[Atividade] Card de questões de múltipla escolha

### ISSUE THREAD

**Issue by santojon** [amadeusproject/uxdesign-html#74]

**Comment by juliotoscano** [comment]
@vinniemoreira Falta integrar à screen Home subject teacher

**Comment by fbormann** [comment]
@juliotoscano  cria uma issue só pra isso, assim a tarefa fica bem dividida para @vinniemoreira (e para os outros também).

**Comment by juliotoscano** [comment]
@fbor

**Comment by juliotoscano** [comment]
Fechei a atividade sem querer.
