### ISSUE TITLE
Inserir HEADER em todas as PAGES já criadas

### ISSUE THREAD

**Issue by juliotoscano** [amadeusproject/uxdesign-html#9]

**Comment by fbormann** [comment]
Falta adicionar a imagem correspondente à essa Issue.

**Comment by fbormann** [comment]
![img_20160830_152402](https://cloud.githubusercontent.com/assets/2985027/18130351/112fd5e6-6f65-11e6-95bf-90ebcd624f2c.jpg)

Imagem adicionada.

**Comment by fbormann** [comment]
Problemas encontrados: 

- Não existe efeito de hover nos elementos que os distingue. 
- Não existe links para outras páginas.
